# Generated by Django 5.1.5 on 2025-02-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=2083)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('discount_percentage', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dimension_width', models.FloatField(blank=True, null=True)),
                ('dimension_height', models.FloatField(blank=True, null=True)),
                ('dimension_depth', models.FloatField(blank=True, null=True)),
                ('warranty_information', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_information', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=50, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_order_quantity', models.IntegerField(blank=True, null=True)),
                ('meta_created_at', models.DateTimeField(blank=True, null=True)),
                ('meta_updated_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=2083, null=True)),
                ('categories', models.ManyToManyField(related_name='products', to='products.category')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_image', to='products.productimage')),
                ('images', models.ManyToManyField(related_name='product_images', to='products.productimage')),
                ('tags', models.ManyToManyField(related_name='tags', to='products.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
